// <auto-generated />
using System;
using ARAP.Modules.ResearchProposal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ARAP.Modules.ResearchProposal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResearchProposalDbContext))]
    partial class ResearchProposalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research_proposal")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ARAP.Modules.ResearchProposal.Domain.Aggregates.ResearchProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("abstract");

                    b.Property<Guid>("AdvisorId")
                        .HasColumnType("uuid")
                        .HasColumnName("advisor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("ResearchQuestion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("research_question");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_comments");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId")
                        .HasDatabaseName("ix_research_proposals_advisor_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_research_proposals_created_at");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_research_proposals_state");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_research_proposals_student_id");

                    b.ToTable("research_proposals", "research_proposal");
                });

            modelBuilder.Entity("ARAP.Modules.ResearchProposal.Domain.Aggregates.ResearchProposal", b =>
                {
                    b.OwnsMany("ARAP.Modules.ResearchProposal.Domain.Entities.Milestone", "Milestones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletionDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completion_date");

                            b1.Property<DateTime>("Deadline")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deadline");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("description");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("type");

                            b1.Property<Guid>("research_proposal_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("research_proposal_id");

                            b1.ToTable("milestones", "research_proposal");

                            b1.WithOwner()
                                .HasForeignKey("research_proposal_id");
                        });

                    b.Navigation("Milestones");
                });
#pragma warning restore 612, 618
        }
    }
}
